---
title: "Article 3: Newly discovered gene may give ‘sea pickles’ their glow."
description: |
  In this third article, scientists have found how pyrosomes produce their light!
author:
  - name: De Tandt Bastien
    url: {}
date: "`November 07, 2020`"
categories:
  - "English for Science"
preview: Image3/Pyrosoma-B12_3862.jpg
#preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### I - SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: [https://www.sciencedaily.com/releases/2020/10/201020131344.htm?fbclid=IwAR1h8ouv_JRcbTsg-uzMx-n5KQX9lLgEvHupmd4_mSQebilfvMfcrzni8z8](https://www.sciencedaily.com/releases/2020/10/201020131344.htm?fbclid=IwAR1h8ouv_JRcbTsg-uzMx-n5KQX9lLgEvHupmd4_mSQebilfvMfcrzni8z8)

October 20, 2020

Word count : 646

### II - VOCABULARY: 

| Word from the text | Synonym/definition in English                   | French translation      |
| ------------------ | ----------------------------------------------- | ----------------------- |
| chordate           | Relating to a phylum chordata                   | Chordés                 |
| So-called          | Commonly named                                  | Ce qu’on appelle        |
| Free-floating      | Not attached to anything                        | Flottant                |
| To reverberate     | Echo or rebound                                 | Se répercuter           |
| Sea squirt         | Variety of marine creature                      | Tunicier                |
| Throughout         | During all of                                   | Tout au long            |
| To conduct         | Carry out                                       | mener                   |
| among              | Member of                                       | parmi                   |
| Baseline           | Guideline                                       | Point de comparaison    |
| Off the coast      | In water near shore                             | Au large                |
| Outfitted          | equipped                                        | Equipé                  |
| Submersible        | submarine                                       | Navire submersible      |
| Squishy            | Soft and wet                                    | Spongieux               |
| Gently             | With care                                       | Avec douceur, doucement |
| Zooid              | Single animal that is part of a colonial animal | Zooïde                  |
| Display            | demonstration                                   | Démonstration           |
| To trigger         | provoke                                         | Provoquer               |
| Elusive            | Avoids answering                                | Evasif                  |
| Pathway            | Path                                            | Chemin, voie            |
| To rely on         | Depend on                                       | Compter sur             |
| Substrate          | Biology : surface, support                      | substrat                |
| Further            | More extended                                   | Plus approfondi         |
| Bloom              | Efflorescence                                   | Efflorescence           |
| To match           | Go together                                     | Aller ensemble          |
| Indeed             | Certainly                                       | Effectivement           |
| Seemingly          | Visibly                                         | Apparement              |
| Strikingly         | Impressively                                    | Remarquablement         |
| Convergent         | That meet or come together                      | convergent              |
| Pattern            | A design on fabric, paper etc                   | Motif                   |

### III - ANALYSIS TABLE ABOUT THE STUDY 

|                                        	|                                                                                                                                                                                                                                                                                                                                                                                                                                         	|
|----------------------------------------	|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| **Researchers?**                       	| Michael Tessler<br><br>Jean P. Gaffney<br><br>Anderson G. Oliveira<br><br>Andrew Guarnaccia<br><br>Krista C. Dobi<br><br>Nehaben A. Gujarati<br><br>Moira Galbraith<br><br>Jeremy D. Mirza<br><br>John S. Sparks<br><br>Vincent A. Pieribone<br><br>Robert J. Wood<br><br>David F. Gruber                                                                                                                                               	|
| **Published in? when (if mentioned)?** 	| Scientific Reports (October 20, 2020)                                                                                                                                                                                                                                                                                                                                                                                                   	|
| **General topic**                      	| The discovery of a bioluminescent gene in chordate                                                                                                                                                                                                                                                                                                                                                                                      	|
| **Procedure/ what was examined**       	| - They captured sea pickles using a submarine with soft robotic hands<br><br>- They sequenced their RNA                                                                                                                                                                                                                                                                                                                                 	|
| **Conclusions/ discovery**             	| 1. There is a gene shared with some animals that could be responsible for bioluminescence<br><br>2. The machanism rely on a chemical reaction<br><br>3. Mixing coelenterazine with the animal give bioluminescence  <br><br>4. The gene produce light by expressing it in a bacterial colony and adding coelenterazine <br><br>5. These type of gene evolved convergently from a baseline gene<br><br>6. The animal makes its own light 	|
| **Remaining questions**                	| None                                                                                                                                                                                                                                                                                                                                                                                                                                    	|



