---
title: "Article 5: Amber-encased fossil shines light on evolution of bioluminescent insects"
description: |
  Preserved with 'life-like' fidelity, beetle from the Cretaceous is fireflies' missing fossil link.
author:
  - name: De Tandt Bastien
    url: {}
date: "`February 06, 2021`"
categories:
  - "English for Science"
preview: Image5/Cretophengodes azari (in amber).jpg
#preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### I - SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: [https://www.sciencedaily.com/releases/2021/01/210119194401.htm?fbclid=IwAR3FKFt7LhEsKep-smobciwa3ll3_yjm5nxJ1k31dQcaC_cSevmVGGunDRA](https://www.sciencedaily.com/releases/2021/01/210119194401.htm?fbclid=IwAR3FKFt7LhEsKep-smobciwa3ll3_yjm5nxJ1k31dQcaC_cSevmVGGunDRA)

January 19, 2021

Word count : 500

### II - VOCABULARY: 

| Word from the text | Synonym/definition in English                                                         | French translation   |
| ------------------ | ------------------------------------------------------------------------------------- | -------------------- |
| To shine           | Direct light                                                                          | éclairer             |
| lifelike           | realistic                                                                             | Très réaliste        |
| amber              | resin                                                                                 | ambre                |
| Beetle             | Insect, bug                                                                           | Scarabée, coléoptère |
| (to) shed light    | Clarify, explain                                                                      | éclairer             |
| Cretaceous         | A geological period                                                                   | Le Crétacé           |
| Fireflies          | Flying insect that glows                                                              | Ver luisant, luciole |
| relatives          | Linked to                                                                             | Relative             |
| To ward off        | To avert                                                                              | prévenir             |
| unsuspecting       | Unaware of                                                                            | Peu méfiant          |
| Soft-bodied        | Having a soft body                                                                    | Corps mou            |
| scant              | little                                                                                | Peu de               |
| cretophengodes     | A fossil-light-producing beetle from Cretaceous Burmese amber (100 million years old) | crétophengodes       |
| rhagophthalmidae   | A family of beetles which have bioluminescent organs                                  | rhagophthalmidae     |
| phengodidae        | A family of beetles related to the rhagophthalmidae                                   | phengodidae          |
| Heterogeneous      | diverse                                                                               | hétérogène           |
| entomologist       | Specialist in insects                                                                 | entomologiste        |
| Unrelated          | Not connected                                                                         | Sans lien            |
| Co-opt             | admit                                                                                 | Admettre             |
| striking           | remarkable                                                                            | Saisissant           |
| counterpart        | Equivalent person                                                                     | homologue            |
| To retain          | keep                                                                                  | Garder, conserver    |
| adulthood          | Full development                                                                      | Âge adulte           |
| Overlooked         | neglected                                                                             | Oublié, omis         |

### III - ANALYSIS TABLE ABOUT THE STUDY 

|                                        |                                                                                                                                                                                                                                                                                                                                                                                   |
| -------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Researchers?**                       | Yan-Da Li

Robin Kundrata

Erik Tihelka

Zhenhua Liu

Diying Huang

Chenyang Cai.                                                                                                                                                                                                                                                                                                 |
| **Published in? when (if mentioned)?** | The royal society (January 20, 2021).                                                                                                                                                                                                                                                                                                                                             |
| **General topic**                      | A fossil, preserved in amber, of a bioluminescent beetle have been discovered.                                                                                                                                                                                                                                                                                                    |
| **Procedure/ what was examined**       | · Researchers examined the fossil of the beetle.

· They examined its light organ.

· They compared it to living family of beetle                                                                                                                                                                                                                                                 |
| **Conclusions/ discovery**             | 1. Adult beetle were able to produce light 100 million years ago

2. The fossil beetle is an extinct relative of living family of beetle

3. It will help to understand how bioluminescent beetles evolved and how to classify them.

4. Light was originally used by larvae as a defensive mechanism to avert predator

5. The adults adopted bioluminescence to search for mate |
| **Remaining questions**                | None                                                                                                                                                                                                                                                                                                                                                                              |
