---
title: "Article 4: Bioluminescent tag to detect DNA break repair"
description: |
  Check out how scientist use bioluminescence to fight cancer!
author:
  - name: De Tandt Bastien
    url: {}
date: "`December 04, 2020`"
categories:
  - "English for Science"
preview: Image4/DNA.jpg
#preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### I - SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: [https://www.sciencedaily.com/releases/2020/08/200821141154.htm?fbclid=IwAR0Cyv_LiYcH8GYykwuSCqRwtmf-CNz7ba7KC6-NuaapyJ2mG6DoPHF77r8](https://www.sciencedaily.com/releases/2020/08/200821141154.htm?fbclid=IwAR0Cyv_LiYcH8GYykwuSCqRwtmf-CNz7ba7KC6-NuaapyJ2mG6DoPHF77r8)

August 21, 2020

Word count : 466

### II - VOCABULARY: 

| Word from the text | Synonym/definition in English                                                  | French translation |
| ------------------ | ------------------------------------------------------------------------------ | ------------------ |
| tag                | Identification label                                                           | balise             |
| To track           | follow                                                                         | pister             |
| strand             | thread                                                                         | brin               |
| break              | fracture                                                                       | fracture           |
| To monitor         | observe                                                                        | Surveiller         |
| pathway            | path                                                                           | chemin             |
| Cell lines         | cell culture                                                                   | Culture cellulaire |
| such               | So extreme                                                                     | Tel, telle         |
| crucial            | Very important                                                                 | crucial            |
| Inherently         | By nature                                                                      | Par nature         |
| To maintain        | Rate                                                                           | Maintenir          |
| To disrupt         | Cause disorder                                                                 | pertuber           |
| Viability          | feasibility                                                                    | Viabilité          |
|                    |                                                                                |                    |
| Intrinsic          | inherent                                                                       | Intrinsèque        |
| To promote         | Advertise                                                                      | Promouvoir         |
| recurrence         | Further instance of                                                            | Recurrence         |
| malignancy         | Cancer: threat to life                                                         | Malignité          |
| homologous         | similar                                                                        | homologue          |
| pathway            | track                                                                          | chemin             |
| Xenografted        | A tissue graft obtained from a donor of a different species from the recipient | Xénogreffe         |
| Time-consuming     | Taking considerable time                                                       | Prendre du temps   |
| Accuracy           | Degree of correctness                                                          | exactitude         |
| To carry out       | accomplish                                                                     | réaliser           |
| significant        | With meaning                                                                   | Significative      |
| Altered            | changed                                                                        | Modifié, change    |
| induced            | Caused by                                                                      | Causé par          |
| Glioblastomas      | The most common and most aggressive primary brain tumour                       | glioblastome       |
| Glioma             | A brain tumor                                                                  | Gliome             |
| sufficiently       | adequately                                                                     | Suffisamment       |
| Versatile          | Many uses                                                                      | Polyvalent         |
| throughput         | Work rate                                                                      | débit              |
| novel              | new                                                                            | Novateur           |

### III - ANALYSIS TABLE ABOUT THE STUDY 

|                                        	|                                                                                                                                                                                                                                                                                                                 	|
|----------------------------------------	|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| **Researchers?**                       	| Jasper Che-Yung Chien<br><br>Elie Tabet<br><br>Kelsey Pinkham<br><br>Cintia Carla da Hora<br><br>Jason Cheng-Yu Chang<br><br>Steven Lin<br><br>Christian E Badr<br><br>Charles Pink-Kuang Lai                                                                                                                   	|
| **Published in? when (if mentioned)?** 	| Nucleic Acids Research (14 August, 2020)                                                                                                                                                                                                                                                                        	|
| **General topic**                      	| Bioluminescent tag to detect DNA break repair                                                                                                                                                                                                                                                                   	|
| **Procedure/ what was examined**       	| - Use of enzymes responsible for bioluminescence to follow molecules in cell<br><br>- Scientist test it on animals and cell lines<br><br>- They study DNA with this system                                                                                                                                      	|
| **Conclusions/ discovery**             	| 1. Can monitor and detect DNA repair pathways.<br><br>2. It is used to detect two main path of DNA double stranded break<br><br>3. Used to detect altered dynamics for DNA double stranded break caused by some molecule<br><br>4. Can be used to fight cancer<br><br>5. It is an sensitive and accurate system 	|
| **Remaining questions**                	| None                                                                                                                                                                                                                                                                                                            	|
