---
title: "Article 2 : Fireflies shed light on the function of mitochondria"
description: |
  In this second article, we see how bioluminescence is used to monitor the activity of mitochondria.
author:
  - name: De Tandt Bastien
    url: {}
date: "`November 03, 2020`"
#preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### I - SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: [ScienceDaily](https://www.sciencedaily.com/releases/2020/08/200812201330.htm?fbclid=IwAR2cxYqP-IAodpDLYH04DxwtMSB_FVjPX14euOdPEXqWGyQn3DJA7G-S3og)

August 12, 2020

Word count : 611

### II - VOCABULARY: 

| Word from the text | Synonym/definition in English                                                     | French translation |
|--------------------|-----------------------------------------------------------------------------------|--------------------|
| Compound           | Substance                                                                         | Composé            |
| Rodent             | Any small animal that belongs to a group of animals with strong sharp front teeth | Rongeur            |
| To rejuvenate      | To make look younger                                                              | Rajeunir           |
| Intented           | Planned                                                                           | Prévu              |
| Affordable         | Not expensive                                                                     | Abordable          |


### III - ANALYSIS TABLE ABOUT THE STUDY 

|                                           |                                                                                                                                                                 |
|-------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Researchers?                              | Arkadiy A. Bazhin, Riccardo Sinisi, Umberto De Marchi, Aurélie Hermant, Nicolas Sambiagio, Tamara Maric, Ghyslain Budin, Elena A. Goun.                         |
|     Published in? when (if mentioned)?    | Science Daily (August 12, 2020)                                                                                                                                 |
| General topic                             | By making a mice bioluminescent, scientists have found a way to monitor the activity of mitochondria in living organisms                                        |
| Procedure/ what was examined              | Scientists created two molecules and injected it into rodent to create light to see the activity of mitochondria                                                |
| Conclusions/ discovery                    | 1.if mitochondria function less, the animal makes less light, if it functions more, it makes more light  2.older rodents produce less light than the younger one |
| Remaining questions                       | /                                                                                                                                                               |
