---
title: "Article 2 : Fireflies shed light on the function of mitochondria"
description: |
  In this second article, we see how bioluminescence is used to monitor the activity of mitochondria.
author:
  - name: De Tandt Bastien
    url: {}
date: "`November 03, 2020`"
categories:
  - "English for Science"
preview: Image2/Article 2 image.webp
#preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### I - SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: [https://www.sciencedaily.com/releases/2020/08/200812201330.htm?fbclid=IwAR2cxYqP-IAodpDLYH04DxwtMSB_FVjPX14euOdPEXqWGyQn3DJA7G-S3og](https://www.sciencedaily.com/releases/2020/08/200812201330.htm?fbclid=IwAR2cxYqP-IAodpDLYH04DxwtMSB_FVjPX14euOdPEXqWGyQn3DJA7G-S3og)

August 12, 2020

Word count : 611

### II - VOCABULARY: 

| Word from the text | Synonym/definition in English                                                                          | French translation  |
| ------------------ | ------------------------------------------------------------------------------------------------------ | ------------------- |
| effectiveness      | Ability to accomplish aim                                                                              | efficacité          |
| increasingly       | More and more                                                                                          | De plus en plus     |
| (to) rely on       | Depend on                                                                                              | Compter sur         |
| (to) shed light on | Clear up                                                                                               | éclairer            |
| At bay             | At a distance                                                                                          | À distance          |
| unmistakable       | Clear, obvious                                                                                         | évident             |
| clue               | Hint, evidence                                                                                         | indice              |
| impaired           | damaged                                                                                                | pertubé             |
| mice               | Plural of mouse, a small rodent                                                                        | souris              |
| To express         | say                                                                                                    | exprimer            |
| luciferase         | The enzyme responsible for bioluminescence in some organisms                                           | luciférase          |
| Luciferin          | a pigment occurring in luminescent organisms, as fireflies, that emits light when undergoing oxidation | Luciférine          |
| Compound           | Substance                                                                                              | Composé             |
| Rodent             | Any small animal that belongs to a group of animals with strong sharp front teeth                      | Rongeur             |
| Outwards           | Towards the outside                                                                                    | Vers l’extérieur    |
| To let in          | Allow to pass                                                                                          | Laisser passer      |
| therefore          | As a consequence                                                                                       | donc                |
| To carry out       | Perform, conduct                                                                                       | Effectuer, réaliser |
| To rejuvenate      | To make look younger                                                                                   | Rajeunir            |
| To monitor         | observe                                                                                                | surveiller          |
| Intended           | Planned                                                                                                | Prévu               |
| sensitive          | Instruments: detects small changes                                                                     | sensible            |
| Affordable         | Not expensive                                                                                          | Abordable           |
| implement          | Put into effect                                                                                        | Mettre en oeuvre    |

### III - ANALYSIS TABLE ABOUT THE STUDY 

|                                        	|                                                                                                                                                                                                                                                                                                                                                                            	|
|----------------------------------------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| **Researchers?**                       	| Arkadiy A. Bazhin<br><br>Riccardo Sinisi<br><br>Umberto De Marchi<br><br>Aurélie Hermant<br><br>Nicolas Sambiagio<br><br>Tamara Maric<br><br>Ghyslain Budin<br><br>Elena A. Goun                                                                                                                                                                                           	|
| **Published in? when (if mentioned)?** 	| Nature (August 10, 2020)                                                                                                                                                                                                                                                                                                                                                   	|
| **General topic**                      	| A protocol to monitor the activity of mitochondria in living organisms                                                                                                                                                                                                                                                                                                     	|
| **Procedure/ what was examined**       	| - Scientists made two molecules and gave it to animals to make bioluminescence<br><br>- They inject a substance to rejuvenate mitochondria<br><br>- They did the experiment on rodents and animals models of cancer                                                                                                                                                      	|
| **Conclusions/ discovery**             	| 1. Less light is produced if the mitochondria functions less<br><br>2. Older mice produce less light<br><br>3. Younger mice have a higher potential membrane<br><br>4. Rodents with the substance produce more light<br><br>5. Could be helpful to create anticancer drug and help cure obesity<br><br>6. The method is sensitive, not expensive and easy to put into effect 	|
| **Remaining questions**                	| None                                                                                                                                                                                                                                                                                                                                                                       	|
