---
title: "My English Activity Log : MEAL"
author:
  - name: "De Tandt Bastien" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---

> September 2020

**Sept. 12th:** I began the season 7 of an American TV show, [*The 100*](https://en.wikipedia.org/wiki/The_100_%28TV_series%29). It's the last season of the show so I'm not going to spoil anyone but to sum up, it's about the last people of the human kind who live on a spatial station called "The Ark" and 100 teenagers are sent to the earth to see if it's survivable because hundred years ago, a nuclear war decimated the planet.
I watch it in English with English subtitles since the 1st season. 

**Sept. 19th:** I watched the second episode of the 7th season of the serie *The 100*.

**Sept. 22nd:** I have downloaded an app called [*BBC news*](https://www.bbc.com/news), it is a broadcast application about news around the world. My English teacher, Ms. Ingrid Lancker, told us to have it on our phone so we can discuss about news during the class.

**Sept. 26th:** Like almost every weekend, i watched another episode of the serie *The 100*, it's the third one. 

> October 2020

**Oct. 03rd:** I saw the fourth episode of *The 100*.

**Oct. 10th:** I visioned the fifth episode of *The 100*

**Oct. 17th:** I watched the sixth episode but I felt asleep at the end, I might have to watch it again to understand what is happening in the next episode.

**Oct. 21st:** I saw a video on YouTube from the channel [*Kurzgesagt*](https://www.youtube.com/c/inanutshell/videos). The video was about drug war and why it is a failure, . It was really interesting and I highly recommend you to watch it, you can watch it by clicking [here](https://www.youtube.com/watch?v=wJUXLqNHCaI) ! The channel is a channel about popularization of various subjects, it’s an English channel and has over 13 millions subscribers!

**Oct. 24th:** This time, I did not watched an episode of the serie but I watched a movie on Netflix called [*Back to the futur*](https://en.wikipedia.org/wiki/Back_to_the_Future), in English of course. It is a really good movie and a famous one ! I don't think that I have to explain to you what the movie is about.

> November 2020

**Nov. 1st:** I watched [*Back to the futur II*](https://www.imdb.com/title/tt0096874/)on Netflix.

**Now. 2nd:** I watched [*The Warrior Kingdoms of the Weaver Ant*](https://www.youtube.com/watch?v=B3QTAgHlwEg&t=24s) of the channel [*Kurzgesagt*](https://www.youtube.com/c/inanutshell/videos). A really interesting video about war in the kingdom of ants!

**Nov. 6th:** I did a quiz on Quizlet about keypoints in Unit 2 of the MCSE. [Quizlet](https://quizlet.com/latest) is a website that helps you studying with flashcards, I find it really usefull when it comes to vocabulary !

**Nov. 14th:** I set up my social networks in English. I hope it will me to use English daily and to get used every day terms.

**Nov. 21th:** I watched [*Wild wild west*](https://www.imdb.com/title/tt0120891/), it is a comedy movie starring Will Smith.

**Nov. 28th:** I watched [*The 5th Wave*](https://en.wikipedia.org/wiki/The_5th_Wave_%28film%29), it's a film based on the novel of the same name by Rick Yancey.

> December 2020

**In december**, I did not really have time to practise my english because examens were coming and I needed to focus on them.

But overall, I hope everyone reading my blog had a great time for Christmas and the new year's eve despite of the virus !

> January 2021

First of all, Happy new year ! 

Secondly, like I said in december, I had to study for my examens so I did not pratice much my English but I had an English examen too so I obviously studied for it in january.

**Jan. 11th & 12th:** I studied the vocabulary and the grammar for my english examen. I think I did well !

**Jan. 22nd (and the rest of the week):** Examens are finally over, I can take time for myself and relax, so I watched [*The umbrella academy*](https://en.wikipedia.org/wiki/The_Umbrella_Academy_%28TV_series%29) on Netflix, in English with subtitles. It is a serie where people with superpowers have to save the world from the apocalypse.

> February 2021

**Feb. 1st:** Holidays are over and I begin with some English. An opportunity for me to get back into the swing of things.

**Feb. 06th:** I studied the vocabulary of unit 7 & 8 on Quizlet.

**Feb. 09th:** I started watching [*Friends*](https://en.wikipedia.org/wiki/Friends), a very popular series with Jennifer Aniston. I watch the show in English with English subtitles.

**Feb. 14th:** I put all my devices in English like my phone and my computer.

**Feb. 22nd:** I browsered some blogs of my friends in my English class to see what were their subject and to expand my knowledge about different fields (in English of course).

> March 2021

**Mar. 04nd:** I subscribed to [*CircleToonsHD*](https://www.youtube.com/user/CircleToonsHD/videos). It is an an English-speaking youtube channel which makes fun about things in video games. Videos are short but are really fun to watch !

**Mar. 06nd:** I discovered [*PBS Eons*](https://www.youtube.com/c/eons/videos), a really good youtube channel that talks about archeology and paleontology and that in English of course ! I really recommend you to check it out if you are interested in those kind of subjects.

**Mar. 10nd:** Once again, I'm going to talk about a youtube channel, [*videogamedunkey*](https://www.youtube.com/user/videogamedunkey/featured). It is a channel about fun review of videos games. The reason why I'm subscribing to more and more channels in English is because I want to watch and listen to more things in English. I believe it will help me to have a more fluent English in the future.

**Mar. 14nd:** I downloaded several books in English that my professors at the university use to make their lessons. When I have time, I read the chapters that we see with the professor and I try to memorize the vocabulary. It is not easy since it is sometimes very specific but I'm trying my best !

**Mar. 17nd:** I began to watch *Snowpiercer* in English with subtitles on Netflix. It is a serie based on a film and a graphic book, I'm at the season 2 and I must say that this is quite good ! Feel free to check the Wikipedia page [here](https://en.wikipedia.org/wiki/Snowpiercer_%28TV_series%29) if you want to know more about it.

> April 2021

**Apr. 1st:** I started watching [*Outlanders*](https://en.wikipedia.org/wiki/Outlander_%28TV_series%29), it is a series where a nurse of World war II travels back in time to get back in 1743 where she met several scottish warrior, I watch the show in English but they speak with an inaudible scottish accent, I understand nothing but hopefully there are subtitles !

**Apr. 05th:** Apart from watching series, my "pre-blocus" session has started today, I begin to write synthesis for some courses and it even includes English ! As a matter of fact, I often use books and videos that are in English to help me doing synthesis and to help me understand the subject, I believe it will help me improve my English skills in vocabulary related to science, especially biology.

**Apr. 10th:** As part of my English cursus, I have to do two summaries about another blog that is not about my studies (biology). I choosed the blog of Luchino Allix : ["The intricate relation between mathematics and the real world."](https://luchinoa.wordpress.com/) We often say that biologist are not very good in mathematics, so I gave it a try and I do not regret it !

**Apr. 16th:** For the second summary, I visited the blog of Ilènia Furgiuele  :["A meteorite shower"](https://ileniafurgiuele639848139.wordpress.com/introduction/). Since meteorites and life have a narrow link, I found the subject really intersting, that's why I did my second summary about it.
