---
title: "Article 1 : Flashes bright when squeezed tight: How single-celled organisms light up the oceans"
description: |
  In this first article, we begin our journey into my topic, bioluminescence ! We take a closer look to an organism who can produce light and make the oceans shine.
author:
  - name: De Tandt Bastien
    url: {}
date: "`October 22, 2020`"
categories:
  - "English for Science"
preview: Image1/dinoflagellate Pyrocystis lunula.png
#preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### I - SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

Source of the article: [ScienceDaily](https://www.sciencedaily.com/releases/2020/07/200706094132.htm)

July 6, 2020

Word count : 620

### II - VOCABULARY: 

| Word from the text | Synonym/definition in English                                                                  | French translation    |
|--------------------|------------------------------------------------------------------------------------------------|-----------------------|
| Bloom              | The sudden development of conspicuous masses of organisms, as algae on the surface of a lake   | Prolifération         |
| Eerie              | Mysterious, creepy                                                                             | Etrange               |
| Stressed           | The physical force exerted on one thing by another                                             | Sous contrainte       |
| To trigger         | To cause or begin                                                                              | Déclencher, provoquer |
| Fireflies          | A beetle that comes out at night, having a light\-producing organ at the rear of the abdomen\. | Ver luisant, luciole  |
| Indentation        | A cut, gap or mark in the edge or surface of something                                         | Indentation           |
| Spurious           | Not authentic                                                                                  | Faux, fallacieux      |
| To scare off       | To fill or be filled with fear or alarm                                                        | Effrayer              |

### III - ANALYSIS TABLE ABOUT THE STUDY 

|                                           |                                                                                                                                                                                                                                                    |
|-------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Researchers?                              | University of Cambridge,  Malzlyar Jalaal, Nico Schramma, Antoine Dode, Hélène de Maleprade, Christophe Raufaste and Raymond E. Goldstein                                                                                                          |
|     Published in? when (if mentioned)?    | Science daily (6 July 2020)                                                                                                                                                                                                                        |
| General topic                             | How Pyrocystis lunula produces light                                                                                                                                                                                                               |
| Procedure/ what was examined              | They used experimental tools based on micromanipulation and high-speed imaging to visualize light production on the single-cell level                                                                                                              |
| Conclusions/ discovery                    | 1.Production of light when cell wall deformed by mechanical forces.  2.Brightness of the flash depends on depth of the deformation and the rate at which it is imposed  3.Mechanism related to ion channels  4.Use of light to scare off predators  |
| Remaining questions                       | /                                                                                                                                                                                                                                                  |

